-- ============================================================
--  SUPERSEDED — nothing to run here. Safe to delete this file.
--
--  This added a checklist column that was replaced by multiple
--  notes before it ever went live. Run 06_jobs_notes.sql instead:
--  it covers everything. If this file was run earlier, the empty
--  `subtasks` column it added is harmless and can stay.
-- ============================================================
